// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Cover       *string `json:"cover"`
	IsPrivate   bool    `json:"isPrivate"`
	Type        int     `json:"type"`
	Frequency   int     `json:"frequency"`
	UpdatedAt   string  `json:"updatedAt"`
	CreatedAt   string  `json:"createdAt"`
}

type NewBook struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Cover       *string `json:"cover"`
	IsPrivate   bool    `json:"isPrivate"`
	Type        int     `json:"type"`
	Frequency   int     `json:"frequency"`
}

type Note struct {
	ID          string   `json:"id"`
	Text        string   `json:"text"`
	Images      []string `json:"images"`
	Author      *User    `json:"author"`
	UpvoteCount int      `json:"upvoteCount"`
	UpdatedAt   string   `json:"updatedAt"`
	CreatedAt   string   `json:"createdAt"`
}

type User struct {
	ID        string  `json:"id"`
	Mobile    string  `json:"mobile"`
	ShareFlag string  `json:"shareFlag"`
	Avatar    *string `json:"avatar"`
	Signature *string `json:"signature"`
	Nickname  *string `json:"nickname"`
}
